# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: |
      dotnet build --configuration $(buildConfiguration)
      dotnet test Digimarc.NTiff.Test --logger "trx;LogFileName=results.trx"
  - task: PublishLinuxTestResults
    inputs:
      testResultsFormat: 'VSTest' 
      testResultsFiles: 'Digimarc.NTiff.Test/TestResults/*.xml' 
 
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
